- name: Remove tailscale instance
  remote_user: 'paperspace'
  hosts: remote
  gather_facts: yes
  vars_files:
    - ../secrets.yml
  roles:
    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ vault_tailscale_key }}"
        state: absent

- name: Destroy infrastructure
  hosts: localhost
  roles:
    - destroy


