- name: Deploy infrastructure and add to inventory
  hosts: localhost
  roles:
    - setup

- hosts: remote
  gather_facts: yes
  remote_user: 'paperspace'
  roles:
    - oobabooga

- hosts: remote
  remote_user: 'paperspace'
  gather_facts: yes
  vars_files:
    - ../secrets.yml
  roles:
    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ tailscale_key }}"
        verbose: true
