- name: Basic deploy of a service
  community.general.terraform:
    project_path: '{{ playbook_dir }}/../terraform'
    variables_files:
      - '{{ playbook_dir }}/../terraform/secrets.tfvars'
    state: present
  register: terraform_output

- name: Set tailscale_key for all hosts
  set_fact:
    tailscale_key: "{{ tailscale_key }}"
  delegate_to: all

- name: Extract Public IP
  set_fact:
    machine_public_ip: "{{ terraform_output.outputs['public_ip'].value }}"
  run_once: true

- add_host:
    name: "{{ machine_public_ip }}"
    group: remote
